Training Records Management System/Pages/MarksPages/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ICT_TRMS.Models;
using Training_Records_Management_System.Data;
using Microsoft.EntityFrameworkCore;

namespace Training_Records_Management_System.Pages.MarksPages
{
    public class CreateModel : PageModel
    {
        private readonly ProjectContext _context;

        public CreateModel(ProjectContext context)
        {
            _context = context;
        }
        public List<SelectListItem> Options { get; set; }

        [BindProperty]
        public StudentMarks StudentMarks { get; set; } = default!;

        public Student Student { get; set; } = default!;

        public async Task<IActionResult> OnGet(int? id)
        {
            if (id == null || _context.Student == null)
            {
                return NotFound();
            }
            var student = await _context.Student.FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }
            else
            {
                Student = student;
            }
            if (_context.Subject == null)
            {
                return NotFound();

            }
            Options = _context.Subject.Select(a =>
                                  new SelectListItem
                                  {
                                      Value = a.ID.ToString(),
                                      Text = a.Title
                                  }).ToList();

            return Page();
        }


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || _context.StudentMarks == null || StudentMarks == null)
            {
                return Page();
            }
            _context.StudentMarks.Add(StudentMarks);
            await _context.SaveChangesAsync();

            return Redirect("/StudentPages/Details?id="+StudentMarks.StudentId );
        }
    }
}

Training Records Management System/Pages/MarksPages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICT_TRMS.Models;
using Training_Records_Management_System.Data;

namespace Training_Records_Management_System.Pages.MarksPages
{
    public class EditModel : PageModel
    {
        private readonly Training_Records_Management_System.Data.ProjectContext _context;

        public EditModel(Training_Records_Management_System.Data.ProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
        public StudentMarks StudentMarks { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.StudentMarks == null)
            {
                return NotFound();
            }

            var studentmarks =  await _context.StudentMarks.FirstOrDefaultAsync(m => m.Id == id);
            if (studentmarks == null)
            {
                return NotFound();
            }
            StudentMarks = studentmarks;

            var student = await _context.Student.FirstOrDefaultAsync(m => m.Id == StudentMarks.StudentId);
            if (student != null) StudentMarks.Student = student;

            var subject = await _context.Subject.FirstOrDefaultAsync(m => m.ID == StudentMarks.SubjectId);
            if (subject != null) StudentMarks.Subject = subject;

            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(StudentMarks).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StudentMarksExists(StudentMarks.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return Redirect("/StudentPages/Details?id=" + StudentMarks.StudentId);
        }

        public async Task<IActionResult> OnPostDelete(int? id)
        {
            if (id == null || _context.StudentMarks == null)
            {
                return NotFound();
            }
            var studentmarks = await _context.StudentMarks.FindAsync(id);

            if (studentmarks != null)
            {
                StudentMarks = studentmarks;
                _context.StudentMarks.Remove(StudentMarks);
                await _context.SaveChangesAsync();
            }

            return Redirect("/StudentPages/Details?id="+studentmarks.StudentId);
        }

        private bool StudentMarksExists(int id)
        {
          return (_context.StudentMarks?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Training Records Management System/Pages/StudentPages/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ICT_TRMS.Models;
using Training_Records_Management_System.Data;

namespace Training_Records_Management_System.Pages.StudentPages
{
    public class CreateModel : PageModel
    {
        private readonly Training_Records_Management_System.Data.ProjectContext _context;

        public CreateModel(Training_Records_Management_System.Data.ProjectContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Student Student { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Student == null || Student == null)
            {
                return Page();
            }

            _context.Student.Add(Student);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Training Records Management System/Pages/StudentPages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICT_TRMS.Models;
using Training_Records_Management_System.Data;

namespace Training_Records_Management_System.Pages.StudentPages
{
    public class EditModel : PageModel
    {
        private readonly Training_Records_Management_System.Data.ProjectContext _context;

        public EditModel(Training_Records_Management_System.Data.ProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Student Student { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Student == null)
            {
                return NotFound();
            }

            var student =  await _context.Student.FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }
            Student = student;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Student).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StudentExists(Student.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool StudentExists(int id)
        {
          return (_context.Student?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Training Records Management System/Pages/SubjectPages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICT_TRMS.Models;
using Training_Records_Management_System.Data;

namespace Training_Records_Management_System.Pages.SubjectPages
{
    public class EditModel : PageModel
    {
        private readonly Training_Records_Management_System.Data.ProjectContext _context;

        public EditModel(Training_Records_Management_System.Data.ProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Subject Subject { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Subject == null)
            {
                return NotFound();
            }

            var subject =  await _context.Subject.FirstOrDefaultAsync(m => m.ID == id);
            if (subject == null)
            {
                return NotFound();
            }
            Subject = subject;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Subject).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SubjectExists(Subject.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool SubjectExists(int id)
        {
          return (_context.Subject?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

Training Records Management System/Pages/MarksPages/Create.cshtml
@page
@model Training_Records_Management_System.Pages.MarksPages.CreateModel

@{
    ViewData["Title"] = "Create";
}

<div class="text-center">
    <h3>Add @Model.Student.LastName @Model.Student.FirstName's Marks</h3>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col">
        </div>
        <div class="col">
            <div class="card">
                <div class="card-body text-centre">
                    <form method="post">
                        <br />
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <input asp-for="StudentMarks.StudentId" class="form-control" value = "@Model.Student.Id" type = "hidden"/>
                            <label asp-for="StudentMarks.SubjectId" class="control-label">Subject</label>
                            <br />
                            <select asp-for="StudentMarks.SubjectId" class="form-control" asp-items="Model.Options"></select>
                        </div>
                        <br />
                        <div class="form-group">
                            <label asp-for="StudentMarks.Mark" class="control-label"></label>
                            <br />
                            <input asp-for="StudentMarks.Mark" class="form-control" />
                            <span asp-validation-for="StudentMarks.Mark" class="text-danger"></span>
                        </div>
                        <br />
                        <div class="form-group  text-end">
                            <a asp-page="/StudentPages/Details" class="btn btn-outline-danger" asp-route-id="@Model.Student?.Id">Cancel</a>
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                        <br />
                    </form>
                </div>
            </div>
        </div>
        <div class="col">
        </div>
    </div>
</div>

<div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Training Records Management System/Pages/MarksPages/Edit.cshtml
@page
@model Training_Records_Management_System.Pages.MarksPages.EditModel

@{
    ViewData["Title"] = "Edit";
}
   <div class="text-center h4">
        @Model.StudentMarks.Student.LastName @Model.StudentMarks.Student.FirstName's Marks
    </div>

<div class="row">
    <div class="col">
    </div>

    <div class="card col">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <form method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="StudentMarks.Id" />
                        <div class="form-group h3 text-center">
                            @Model.StudentMarks.Subject.Title
                            <input asp-for="StudentMarks.StudentId" value="@Model.StudentMarks.StudentId" class="form-control" type="hidden"></input>

                        </div>
                        <div class="form-group">
                            <input asp-for="StudentMarks.SubjectId" value="@Model.StudentMarks.SubjectId" class="form-control" type="hidden"></input>

                        </div>
                        <div class="form-group">
                            <label asp-for="StudentMarks.Mark" class="control-label"></label>
                            <br />
                            <input asp-for="StudentMarks.Mark" class="form-control" />
                            <span asp-validation-for="StudentMarks.Mark" class="text-danger"></span>
                        </div>
                        <br />
                        <div class="form-group text-end">

                            <a asp-page="/StudentPages/Details" asp-route-id="@Model.StudentMarks.StudentId" class="btn btn-outline-primary">Back</a>
                            <input type="submit" value="Save" class="btn btn-primary" />

                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                Delete
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
    </div>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">Are you Sure you want to delete this record?</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="card text-center">
                    <div class="card-body text-centre">
                        @Model.StudentMarks.Subject.Title
                        <div class="h3">
                            @Model.StudentMarks.Mark
                        </div>
                        @Model.StudentMarks.Grade
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form asp-page-handler="delete" asp-route-id="@Model.StudentMarks.Id" method="post">
                    <button class="btn btn-danger"> Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}