Training Records Management System/Pages/MarksPages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICT_TRMS.Models;
using Training_Records_Management_System.Data;

namespace Training_Records_Management_System.Pages.MarksPages
{
    public class EditModel : PageModel
    {
        private readonly Training_Records_Management_System.Data.ProjectContext _context;

        public EditModel(Training_Records_Management_System.Data.ProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
        public StudentMarks StudentMarks { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.StudentMarks == null)
            {
                return NotFound();
            }

            var studentmarks =  await _context.StudentMarks.FirstOrDefaultAsync(m => m.Id == id);
            if (studentmarks == null)
            {
                return NotFound();
            }
            StudentMarks = studentmarks;

            var student = await _context.Student.FirstOrDefaultAsync(m => m.Id == StudentMarks.StudentId);
            if (student != null) StudentMarks.Student = student;

            var subject = await _context.Subject.FirstOrDefaultAsync(m => m.ID == StudentMarks.SubjectId);
            if (subject != null) StudentMarks.Subject = subject;

            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(StudentMarks).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StudentMarksExists(StudentMarks.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return Redirect("/StudentPages/Details?id=" + StudentMarks.StudentId);
        }

        public async Task<IActionResult> OnPostDelete(int? id)
        {
            if (id == null || _context.StudentMarks == null)
            {
                return NotFound();
            }
            var studentmarks = await _context.StudentMarks.FindAsync(id);

            if (studentmarks != null)
            {
                StudentMarks = studentmarks;
                _context.StudentMarks.Remove(StudentMarks);
                await _context.SaveChangesAsync();
            }

            return Redirect("/StudentPages/Details?id="+studentmarks.StudentId);
        }

        private bool StudentMarksExists(int id)
        {
          return (_context.StudentMarks?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Training Records Management System/Pages/StudentPages/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ICT_TRMS.Models;
using Training_Records_Management_System.Data;

namespace Training_Records_Management_System.Pages.StudentPages
{
    public class DeleteModel : PageModel
    {
        private readonly Training_Records_Management_System.Data.ProjectContext _context;

        public DeleteModel(Training_Records_Management_System.Data.ProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Student Student { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Student == null)
            {
                return NotFound();
            }

            var student = await _context.Student.FirstOrDefaultAsync(m => m.Id == id);

            if (student == null)
            {
                return NotFound();
            }
            else 
            {
                Student = student;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Student == null)
            {
                return NotFound();
            }
            var student = await _context.Student.FindAsync(id);

            if (student != null)
            {
                Student = student;
                _context.Student.Remove(Student);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Training Records Management System/Pages/StudentPages/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ICT_TRMS.Models;
using Training_Records_Management_System.Data;

namespace Training_Records_Management_System.Pages.StudentPages
{
    public class DetailsModel : PageModel
    {
        private readonly Training_Records_Management_System.Data.ProjectContext _context;

        public DetailsModel(Training_Records_Management_System.Data.ProjectContext context)
        {
            _context = context;
        }

        public Student Student { get; set; } = default!;

        public List<StudentMarks> StudentsMarks { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Student == null)
            {
                return NotFound();
            }

            var student = await _context.Student.FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }
            else
            {
                Student = student;
            }

            if (_context.StudentMarks != null) StudentsMarks = _context.StudentMarks
                     .Where(a => a.StudentId == id)
                 .Include(s => s.Subject)
                 .ToList();
            Student.Marks = StudentsMarks;
            return Page();
        }
    }
}

Training Records Management System/Pages/StudentPages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICT_TRMS.Models;
using Training_Records_Management_System.Data;

namespace Training_Records_Management_System.Pages.StudentPages
{
    public class EditModel : PageModel
    {
        private readonly Training_Records_Management_System.Data.ProjectContext _context;

        public EditModel(Training_Records_Management_System.Data.ProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Student Student { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Student == null)
            {
                return NotFound();
            }

            var student =  await _context.Student.FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }
            Student = student;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Student).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StudentExists(Student.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool StudentExists(int id)
        {
          return (_context.Student?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Training Records Management System/Pages/SubjectPages/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ICT_TRMS.Models;
using Training_Records_Management_System.Data;

namespace Training_Records_Management_System.Pages.SubjectPages
{
    public class DeleteModel : PageModel
    {
        private readonly Training_Records_Management_System.Data.ProjectContext _context;

        public DeleteModel(Training_Records_Management_System.Data.ProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Subject Subject { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Subject == null)
            {
                return NotFound();
            }

            var subject = await _context.Subject.FirstOrDefaultAsync(m => m.ID == id);

            if (subject == null)
            {
                return NotFound();
            }
            else 
            {
                Subject = subject;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Subject == null)
            {
                return NotFound();
            }
            var subject = await _context.Subject.FindAsync(id);

            if (subject != null)
            {
                Subject = subject;
                _context.Subject.Remove(Subject);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Training Records Management System/Pages/SubjectPages/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ICT_TRMS.Models;
using Training_Records_Management_System.Data;

namespace Training_Records_Management_System.Pages.SubjectPages
{
    public class DetailsModel : PageModel
    {
        private readonly Training_Records_Management_System.Data.ProjectContext _context;

        public DetailsModel(Training_Records_Management_System.Data.ProjectContext context)
        {
            _context = context;
        }

      public Subject Subject { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Subject == null)
            {
                return NotFound();
            }

            var subject = await _context.Subject.FirstOrDefaultAsync(m => m.ID == id);
            if (subject == null)
            {
                return NotFound();
            }
            else 
            {
                Subject = subject;
            }
            return Page();
        }
    }
}

Training Records Management System/Pages/SubjectPages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICT_TRMS.Models;
using Training_Records_Management_System.Data;

namespace Training_Records_Management_System.Pages.SubjectPages
{
    public class EditModel : PageModel
    {
        private readonly Training_Records_Management_System.Data.ProjectContext _context;

        public EditModel(Training_Records_Management_System.Data.ProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Subject Subject { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Subject == null)
            {
                return NotFound();
            }

            var subject =  await _context.Subject.FirstOrDefaultAsync(m => m.ID == id);
            if (subject == null)
            {
                return NotFound();
            }
            Subject = subject;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Subject).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SubjectExists(Subject.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool SubjectExists(int id)
        {
          return (_context.Subject?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

Training Records Management System/Pages/SubjectPages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ICT_TRMS.Models;
using Training_Records_Management_System.Data;

namespace Training_Records_Management_System.Pages.SubjectPages
{
    public class IndexModel : PageModel
    {
        private readonly Training_Records_Management_System.Data.ProjectContext _context;

        public IndexModel(Training_Records_Management_System.Data.ProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Subject Sub { get; set; } = default!;

        public IList<Subject> Subject { get; set; } = default!;

        public async Task OnGetAsync()
        {
            if (_context.Subject != null)
            {
                Subject = await _context.Subject.ToListAsync();
            }
        }

        public async Task<IActionResult> OnPostCreateAsync()
        {
            if (!ModelState.IsValid || _context.Subject == null || Sub == null)
            {
                return Page();
            }

            _context.Subject.Add(Sub);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }

        public async void OnPostLoad(int id)
        {
            if (_context.Subject != null)
            {
                var s = await _context.Subject.FirstOrDefaultAsync(m => m.ID == id);
                if (s != null)
                {
                    Sub = s;
                }
            }
        }


        public async Task<IActionResult> OnPostEditAsync(int id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Sub).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SubjectExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool SubjectExists(int id)
        {
            return (_context.Subject?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

Training Records Management System/Pages/SubjectPages/Delete.cshtml
@page
@model Training_Records_Management_System.Pages.SubjectPages.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<div class="h2">
     Are you sure you would like to delete this subject?
</div>
    <hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Subject.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Subject.Title)
        </dd>
    </dl>
    <br />
    <form method="post">
        <input type="hidden" asp-for="Subject.ID" />
        <a  class="btn btn-outline-success" asp-page="./Index">Cancel</a>
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
</div>

Training Records Management System/Pages/SubjectPages/Details.cshtml
@page
@model Training_Records_Management_System.Pages.SubjectPages.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Subject</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Subject.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Subject.Title)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Subject?.ID">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Training Records Management System/Pages/SubjectPages/Edit.cshtml
@page
@model Training_Records_Management_System.Pages.SubjectPages.EditModel

@{
    ViewData["Title"] = "Edit";
}
<div class="text-center h1">
     Edit Subject
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Subject.ID" />
            <div class="form-group">
                <label asp-for="Subject.Title" class="control-label"></label>
                <input asp-for="Subject.Title" class="form-control" />
                <span asp-validation-for="Subject.Title" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <a class="btn btn-danger" asp-page="./Index">Discard</a>
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Training Records Management System/Pages/SubjectPages/Index.cshtml
@page
@model Training_Records_Management_System.Pages.SubjectPages.IndexModel

@{
    ViewData["Title"] = "Index";
}

<div class="text-center h1">
    Subjects
</div>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Subject[0].Title)
            </th>
            <th class="text-end" style="width: 15%">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createModal">
                    New Subject
                </button>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Subject)
        {
            <tr>
                <td>
                    <form asp-page-handler="load" method="post" asp-route-id="@item.ID">
                        <a id="clickablerow">
                            <input type="submit" id="clickablerow"  data-bs-toggle="modal" data-bs-target="#editModal">
                            @Html.DisplayFor(modelItem => item.Title)
                        </a>
                    </form>
                </td>
                <td class="text-end">
                    <a class="btn btn-danger" asp-page="./Delete" asp-route-id="@item.ID">
                        <img src="~/bin.png" />
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">New Subject</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-page-handler="create" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <label asp-for="Sub.Title" class="control-label h4"></label>
                        <input asp-for="Sub.Title" class="form-control" />
                        <span asp-validation-for="Sub.Title" class="text-danger"></span>
                    </div>
                    <br />
                    <br />
                    <div class="text-end">

                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">Details</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-page-handler="edit" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Sub.ID" />
                    <div class="form-group">
                        <label asp-for="Sub.Title" class="control-label"></label>
                        <input asp-for="Sub.Title" class="form-control" />
                        <span asp-validation-for="Sub.Title" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>